### ISSUE TITLE
Juniper example gives trait `Serialize` not implemented for `std::future::Future` error

### ISSUE THREAD

**Issue by biot023** [actix/examples#408]
Hi -- I'm adapting the code for Juniper like so:

```rust
#[post("/graphql")]                                                    
pub async fn graphql(                                                  
    context: web::Data<Context>,                                       
    schema: web::Data<Arc<Schema>>,                                    
    gql_req: web::Json<GraphQLRequest>,                                
)                                                                      
    -> Result<HttpResponse, actix_web::Error>                          
{                                                                      
    let data = web::block(move || {                                    
        let res = gql_req.execute(&schema, &context);                  
        Ok::<_, serde_json::error::Error>(serde_json::to_string(&res)?)
    })                                                                 
        .await?;                                                       
                                                                       
    Ok(                                                                
        HttpResponse::Ok()                                             
            .content_type("application/json")                          
            .body(data)                                                
    )                                                                  
}                                                                      
```

But I'm getting this error:

> error[E0277]: the trait bound `impl std::future::Future: Serialize` is not satisfied
> Ok::<_, serde_json::error::Error>(serde_json::to_string(&res)?)
> the trait `Serialize` is not implemented for `impl std::future::Future`
> /.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.62/src/ser.rs:2221:17
> T: ?Sized + Serialize,
> required by this bound in `serde_json::to_string`

I've used this example before successfully but I guess not this time.

My Cargo.toml dependencies look like this:

```toml
[dependencies]          
actix-web = "3.3.2"     
actix-rt = "2.0.2"      
env_logger = "0.8.2"    
log = "0.4.14"          
futures = "0.3.12"      
actix-service = "1.0.6" 
juniper = "0.15.3"      
serde = "1.0.123"       
serde_json = "1.0.62"   
serde_derive = "1.0.123"
chrono = "0.4.19"       
mysql = "20.1.0"        
```

Can anybody offer me any advice on how to fix this?
Thanks,
   Doug.
